### GET /
GET http://localhost:8080 HTTP/1.1

### POST /auth/register
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

{
  "first_name": "nejc",
  "last_name": "sakulac",
  "email": "john123@gmail.com",
  "password": "John123!",
  "confirm_password": "John123!"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john8@gmail.com",
  "password": "John123!"
}

### PATCH /users/:id
PATCH http://localhost:8080/users/32fa9e40-57a2-4da8-aa01-8569d2069217 HTTP/1.1
Content-Type: application/json

{
  "first_name": "jebemti mater"
}


### GET /users
GET http://localhost:8080/users HTTP/1.1

### GET /auth
GET http://localhost:8080/auth HTTP/1.1

### POST /auth/signout
POST http://localhost:8080/auth/signout HTTP/1.1


### GET /permissions
GET http://localhost:8080/permissions HTTP/1.1


### POST /permissions
POST http://localhost:8080/permissions HTTP/1.1
Content-Type: application/json

{
  "role_id": "view_users"
}

### GET /roles
GET http://localhost:8080/roles HTTP/1.1

### POST /roles
POST http://localhost:8080/roles HTTP/1.1
Content-Type: application/json

{
  "name": "Admin",
  "permissions": ["1e49349b-ae49-4642-add9-e4b2ba9bec29", "a2aa042c-1e53-4647-a01b-e387006a8973"]
}

### DELETE /roles/:id
DELETE http://localhost:8080/roles/ad58c478-ca2a-4ea3-b0c6-b95cd4fca6b2

### PATCH /roles/:id
PATCH http://localhost:8080/roles/f41ce387-4b08-4f09-821e-97b1adb9b97f
Content-Type: application/json

{
  "name": "Adminn",
  "permissions": ["a2aa042c-1e53-4647-a01b-e387006a8973"]
}


### PATCH /products/:id
PATCH http://localhost:8080/products/4ea07f3a-192f-4118-9b11-32a50f9b07ff HTTP/1.1
Content-Type: application/json

{
  "title": "as (edited)",
  "description": "dasdadasdas (edited)",
  "price": 15,
  "image": null
}

### POST /products
POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
  "title": "New Awesome Widget",
  "description": "This widget does awesome things!",
  "price": 25,
  "image": null
}


